version: '3.7'

services:
  api:
    image: ghcr.io/lampspace/next-commerce-api:latest
    container_name: api-service
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    environment:
      WWWUSER: '${WWWUSER:-1000}'
    networks:
      - next-network
  storefront:
    image: ghcr.io/lampspace/next-commerce-storefront:latest
    container_name: storefront-service
    ports:
      - "3000:3000"
  backoffice:
    image: ghcr.io/lampspace/next-commerce-backoffice:latest
    container_name: backoffice-service
    ports:
      - "3001:3000"
networks:
  next-network: