version: '3.7'

services:
  api:
    image: ghcr.io/lampspace/next-commerce-api:latest
    container_name: api-service
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
  storefront:
    image: ghcr.io/lampspace/next-commerce-storefront:latest
    container_name: storefront-service
    ports:
      - "80:3000"
  backoffice:
    image: ghcr.io/lampspace/next-commerce-backoffice:latest
    container_name: backoffice-service
    ports:
      - "5000:3000"
  postgres:
    image: debezium/postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: next_commerce
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgres: