version: '3.7'

services:
  api:
    image: ghcr.io/lampspace/next-commerce-api:latest
    container_name: api-service
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
    environment:
      WWWUSER: '${WWWUSER:-1000}'
    networks:
      - next-network

networks:
  next-network: