name: API CI

on:
  push:
    branches: [master]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, zip, pcntl, pdo_mysql
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
      - name: Run Tests
        run: vendor/bin/phpunit