name: API CI

on:
  push:
    branches: [master]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yaml'

jobs:
  build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, zip, pcntl, pdo_mysql
      - name: Install dependencies
        run: cd api && composer install --prefer-dist --no-progress --no-interaction
      - name: Copy .env
        run: cd api && cp .env.example .env
      - name: Generate key
        run: cd api && php artisan key:generate
      - name: Run Tests
        run: cd api && vendor/bin/phpunit
  publish:
    name: API Docker Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: ghcr.io/lampspace/next-commerce-api:latest
