name: API CI

on:
  push:
    branches: [develop]
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yaml'

jobs:
  build:
    name: API Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, zip, pcntl, pdo_mysql
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction
        working-directory: api
      - name: Copy .env
        run: cp .env.example .env
        working-directory: api
      - name: Generate key
        run: php artisan key:generate
        working-directory: api
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Docker images
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: ghcr.io/lampspace/next-commerce-api:latest
      
